# Generated by Django 5.1 on 2024-11-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0028_delete_eligibleapplication_remove_loanapp_loan_and_more'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=6)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verified_date', models.DateTimeField(auto_now_add=True)),
                ('verified_by_employee_id', models.CharField(max_length=50)),
                ('verified_by_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=6)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejection_comments', models.TextField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(auto_now_add=True)),
                ('rejected_by_employee_id', models.CharField(max_length=50)),
                ('rejected_by_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=6, unique=True)),
                ('loan_amount', models.DecimalField(choices=[(100000, '100000'), (500000, '500000'), (1000000, '1000000')], decimal_places=2, default=100000, max_digits=10)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('residence_duration', models.CharField(max_length=10)),
                ('employer', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=255)),
                ('bank_phone', models.CharField(max_length=15)),
                ('consent', models.BooleanField()),
                ('document1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document3', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('Application_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Eligible', 'Eligible'), ('Rejected', 'Rejected')], default='submitted', max_length=10)),
                ('Add_rejection_comments', models.TextField(blank=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.register')),
            ],
        ),
    ]
