# Generated by Django 5.1 on 2024-11-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_agreement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='loan_application',
        ),
        migrations.AddField(
            model_name='agreement',
            name='application_number',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='id',
            field=models.BigAutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
