# Generated by Django 5.1.1 on 2024-11-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
