# Generated by Django 5.1 on 2024-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('required_documents', models.TextField(help_text='List required documents, separated by new lines.')),
                ('eligibility_criteria', models.TextField(help_text='List eligibility criteria, separated by new lines.')),
            ],
        ),
    ]
