# Generated by Django 5.1 on 2024-09-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_signup_delete_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='Register',
        ),
    ]
