# Generated by Django 5.1.1 on 2024-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_signup_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('residence_duration', models.CharField(max_length=10)),
                ('employer', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_mortgage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments', models.TextField(blank=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=255)),
                ('bank_phone', models.CharField(max_length=15)),
                ('consent', models.BooleanField()),
            ],
        ),
    ]
