# Generated by Django 5.1.1 on 2024-10-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_loanapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.register'),
        ),
    ]
