# Generated by Django 5.1.1 on 2024-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_loanapp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
