# Generated by Django 5.1.1 on 2024-10-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_loanapp_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapp',
            old_name='document',
            new_name='document1',
        ),
        migrations.AddField(
            model_name='loanapp',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='loanapp',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
