# Generated by Django 5.1.1 on 2024-10-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_loanrequest'),
        ('authentication', '0007_rename_document_loanapp_document1_loanapp_document2_and_more'),
    ]

    operations = [
    ]
