# Generated by Django 5.1.1 on 2024-10-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delete_loanrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapp',
            name='loan_amount',
            field=models.DecimalField(choices=[(100000, '100,000'), (500000, '500,000'), (1000000, '1,000,000')], decimal_places=2, default=100000, max_digits=10),
        ),
    ]
