# Generated by Django 5.1 on 2024-10-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_loanapp_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loanapp',
            name='loan_amount',
            field=models.DecimalField(choices=[(100000, '100000'), (500000, '500000'), (1000000, '1000000')], decimal_places=2, default=100000, max_digits=10),
        ),
    ]
