# Generated by Django 5.1.1 on 2024-10-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_staff_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='rejection_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapp',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
