# Generated by Django 5.1.1 on 2024-10-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_loanapp_rejection_comments_loanapp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapp',
            name='rejection_comments',
        ),
        migrations.RemoveField(
            model_name='loanapp',
            name='status',
        ),
    ]
