# Generated by Django 5.1.1 on 2024-10-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_loanapp_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='Add_rejection_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapp',
            name='Application_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='submitted', max_length=10),
        ),
    ]
