# Generated by Django 5.1.1 on 2024-10-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_loanapp_add_rejection_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapp',
            name='application_number',
        ),
    ]
