# Generated by Django 5.1.1 on 2024-10-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_loanapp_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='application_number',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
