# Generated by Django 5.1 on 2024-10-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_loanapp_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapp',
            name='application_number',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
