# Generated by Django 5.1.1 on 2024-10-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_loanapp_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=6)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejection_comments', models.TextField(blank=True, null=True)),
                ('rejection_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
