# Generated by Django 5.1.1 on 2024-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_rejectedapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedapplications',
            name='rejected_by_employee_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejectedapplications',
            name='rejected_by_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
