# Generated by Django 5.1.1 on 2024-11-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_loanapp_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=6)),
                ('loan_purpose', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verified_date', models.DateTimeField(auto_now_add=True)),
                ('verified_by_employee_id', models.CharField(max_length=50)),
                ('verified_by_name', models.CharField(max_length=100)),
            ],
        ),
    ]
